03:44:42 PM: DEBUG [logger_base.py:12] Prueba debug
